---
- hosts: all
  connection: local

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']

  tasks:
    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
