---
- hosts: all
  connection: local

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']

  tasks:
    - name: install atom packages
      shell: >
        apm list --bare | grep -E "^{{ item }}@"
        && echo "Already installed."
        || apm install "{{ item }}"
      loop: "{{ atom_packages }}"
      register: apm_result
      changed_when: "'Already installed.' not in apm_result.stdout"
      tags: ['atom']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
