---
- hosts: all
  connection: local

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

  tasks:
    - name: install visual studio code extensions
      shell: >
        code --list-extensions | grep -E "^{{ item }}"
        && echo "Already installed."
        || code --install-extension "{{ item }}"
      loop: '{{ visual_studio_code_extensions }}'
      register: vsc_result
      changed_when: "'Already installed.' not in vsc_result.stdout"
      tags: ['vsc']

    - name: Run configured post-provision ansible task files.
      include_tasks: '{{ outer_item }}'
      loop_control:
        loop_var: outer_item
      with_fileglob: '{{ post_provision_tasks|default(omit) }}'
